### ISSUE TITLE
이슈사항 처리 

### ISSUE THREAD

**Issue by keepinmindsh** [bas4432/CalendarProject#4]
[Mirmee171]
- 들여쓰기 여백 체크 
- ReactJS에서 start, end date를 바탕으로 기간을 조회해서 Calendar에 뿌려주세요. 
- 함수명 오타 체크하기 
- 변수명 축약하지 말것 
- if/else -> if 문만 쓰는 것을 코딩하기 
- Component 기반으로 분리 작업 요청 드림.

**Comment by Mirmee171** [comment]
- [ ]

**Comment by keepinmindsh** [comment]
[Mirmee171]
- 테스트 코드 우선이다! 테스트 코드가 작성되어야 하며, 업무 도메인 개발이 필요함! 
- @ResponseBody 의 역할 ->  Cotroller / RestController [ 문서작성 ]
- MVC 에서 각 Model, View, Controller의 역할과 Controller와 Service(Business Level)의 정의 방식 
- 주석 제거 요청 
- 데이터 타입, 업무 도메인에 따라서 변수명 정의 재검토 
- 좌측 Calendar 에 대해서 1차 화면 뿌리기 
- DB 설계 부분의 화면 개발 - 금일부터 진행

**Comment by Mirmee171** [comment]
- 좌측 Calendar에 1차 화면 뿌리기 전, 테스트 코드를 익히기 위해 하단의 페이지를 기반으로 공부 및 공부 예정입니다.
1. https://spring.io/guides/gs/testing-web/ (현재 참고중)
2. https://medium.com/@sheikarbaz5/spring-boot-with-tdd-test-driven-development-part-i-be1b90da51e (참고 예정)
- DB 설계 부분의 화면 개발 완료하여 제 계정 깃에 올렸습니다.
- 나머지 사항은 모두 수정 혹은 readme에 업데이트 완료했습니다.
